apiVersion: v1
kind: ConfigMap
metadata:
  name: blue-index
data:
  index.html: |
    <html>
      <body style="background-color:#e0f7ff;">
        <h1>🟦 Blue Deployment</h1>
      </body>
    </html>
