apiVersion: v1
kind: ConfigMap
metadata:
  name: green-index
data:
  index.html: |
    <html>
      <body style="background-color:#e0ffe0;">
        <h1>🟩 Green Deployment</h1>
      </body>
    </html>
