name: OWASP Dependency Check

on:
  pull_request:
    branches: [main, develop, release]

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3.5.3

      - name: Install OWASP Dependency-Check
        run: |
          curl -L -o dependency-check.zip https://github.com/jeremylong/DependencyCheck/releases/download/v8.4.0/dependency-check-8.4.0-release.zip
          unzip dependency-check.zip -d dc
          chmod +x dc/dependency-check/bin/dependency-check.sh

      - name: Run Dependency Check Scan
        run: |
          ./dc/dependency-check/bin/dependency-check.sh \
             --project "firefly" \
             --scan . \
             --format "HTML" \
             --out owasp-report \
             --disableAssembly

      - name: Upload OWASP Report
        uses: actions/upload-artifact@v4
        with:
          name: owasp-dependency-report
          path: owasp-report/dependency-check-report.html
          retention-days: 7
          compression-level: 6
