name: 'Code - Run Sonarcloud'

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop

env:
  DB_CONNECTION: sqlite
  APP_KEY: TestTestTestTestTestTestTestTest

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP with Xdebug
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          coverage: xdebug
          extensions: mbstring, pdo, sqlite3

      - name: Copy testing config
        run: cp .env.testing .env

      - name: Install PHP dependencies
        run: composer install --prefer-dist --no-interaction --no-progress --no-scripts

      - name: Download SQLite test database
        run: |
          mkdir -p storage/database
          wget -q https://github.com/CheckMateFZ/firefly-iii/raw/main/test-database.sqlite -O storage/database/database.sqlite

      - name: Run Firefly DB upgrade
        run: php artisan firefly-iii:upgrade-database

      - name: Run integrity check
        run: php artisan firefly-iii:report-integrity

      - name: Run test suite with coverage
        run: composer coverage

      - name: Fix coverage file paths
        run: sed -i 's@'$GITHUB_WORKSPACE'@/github/workspace/@g' coverage.xml

      - name: Run SonarCloud Scan (official)
        uses: SonarSource/sonarqube-scan-action@v5.0.0
        with:
          args: >
            -Dsonar.projectKey=CheckMateFZ_firefly-iii
            -Dsonar.organization=devsecops-project-fireflyiii
            -Dsonar.sources=.
            -Dsonar.language=php
            -Dsonar.php.coverage.reportPaths=coverage.xml
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
