name: Container Security - Trivy Scan

on:
  pull_request:
    branches:
      - develop
      - release

jobs:
  trivy-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Trivy (Official Script)
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin

      - name: Build Safe Docker Image
        run: |
          docker build -t firefly-safe -f .devsecops-tests/trivy/Dockerfile.safe .

      - name: Build Vulnerable Docker Image
        run: |
          docker build -t firefly-vuln -f .devsecops-tests/trivy/Dockerfile.vuln .

      - name: Scan Safe Image with Trivy
        run: |
          trivy image --severity HIGH,CRITICAL --format table --output safe-report.txt firefly-safe

      - name: Scan Vulnerable Image with Trivy
        run: |
          trivy image --severity HIGH,CRITICAL --exit-code 1 --format table --output vuln-report.txt firefly-vuln

      - name: Upload Trivy Reports
        uses: actions/upload-artifact@v4
        with:
          name: trivy-reports
          path: |
            safe-report.txt
            vuln-report.txt
