name: DAST - OWASP ZAP (Docker)

on:
  pull_request:
    branches:
      - develop
      - release

jobs:
  zap-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run ZAP Baseline Scan
        run: |
          docker run -v $(pwd):/zap/wrk/:rw ghcr.io/zaproxy/zaproxy:stable zap-baseline.py \
            -t https://demo.firefly-iii.org \
            -g gen.conf \
            -r zap_report.html \
            -J zap_report.json \
            -x zap_report.xml

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v3
        with:
          name: zap-report
          path: zap_report.html
